apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ruby-pinger.fullname" . }}-config
  labels:
    {{- include "ruby-pinger.labels" . | nindent 4 }}
data:
  config.yaml: |
    ---
      dataservice-host: "http://{{ .Values.jaegerrd.dataservice.host }}"
      dataservice-port: {{ .Values.jaegerrd.dataservice.port }}
      frontend-host: "http://{{ .Values.jaegerrd.web.host }}"
      frontend-port: {{ .Values.jaegerrd.web.port }}
      loadbalancer-host: "http://{{ .Values.jaegerrd.loadbalancer.host }}"
      loadbalancer-port: {{ .Values.jaegerrd.loadbalancer.port }}
      wrong-host: http://wrong
      wrong-port: 4242
      service-name: "{{ .Values.jaeger.serviceName }}"
      jaeger-host: "{{ .Values.jaeger.host }}"
      jaeger-port: "{{ .Values.jaeger.port }}"
