{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ruby-pinger.serviceAccountName" . }}
  labels:
{{ include "ruby-pinger.labels" . | nindent 4 }}
{{- end -}}
