apiVersion: v2
name: ruby-pinger
description: Ruby Pinger application Helm chart for Kubernetes
type: application

# Do not update version values below, they are set to minimal values to make 'helm lint' happy.
# Actual versions are set by 'helm package' in the root Makefile when Chart is packaged
version: 0.0.1
appVersion: 0.0.1
