{{/* vim: set filetype=helm: */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger-rd.fullname" . }}-web
  labels:
    {{- include "jaeger-rd.web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jaeger-rd.web.selectorLabels" . | nindent 4 }}
