{{/* vim: set filetype=helm: */}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jaeger-rd.serviceAccountName" . }}
  labels:
{{ include "jaeger-rd.commonLabels" . | nindent 4 }}
{{- end -}}
