image:
  pullPolicy: Always

imagePullSecrets:
  - name: "ecr-docker-config"

ingress:
  enabled: true
  hosts:
    - host: "pinger.192-168-56-103.nip.io"
      paths: ["/"]

jaegerrd:
  dataservice:
    host: "blog-jaeger-rd-dataservice"
    port: 4000
  loadbalancer:
    host: "blog-jaeger-rd-loadbalancer"
    port: 2001
  web:
    host: "blog-jaeger-rd-web"
    port: 3000

jaeger:
  serviceName: "pinger"
  host: "blog-tracing-agent"
  port: 6831
