FROM golang:1.13.7-alpine AS build

ENV GOPATH /go
WORKDIR /go/src/jaeger-rd/dataservice

COPY dataservice /go/src/jaeger-rd/dataservice

RUN go build -o /go/bin/dataservice -mod=vendor

FROM alpine:3.11.3

# bash and coreutils are required for 'wait-for' script
RUN apk update && apk upgrade && apk add bash coreutils curl

COPY wait-for /usr/local/bin/

# Install golang-migrate for DB schema migration
WORKDIR /tmp
COPY data.sh ./
RUN bash data.sh
#RUN curl -L -O https://github.com/golang-migrate/migrate/releases/download/v4.8.0/migrate.linux-amd64.tar.gz && \
#    echo "c92ff8b5085b0de4c027c8c3069529c5e097b02e45effc7c21c46d5952bbf509  migrate.linux-amd64.tar.gz" | sha256sum -c - && \
#    tar xzf migrate.linux-amd64.tar.gz && \
#    mv migrate.linux-amd64 /usr/local/bin/migrate && \
#    rm -f migrate.linux-amd64.tar.gz

WORKDIR /

COPY db/migrations /migrations

COPY --from=build /go/bin/dataservice /usr/local/bin/

ENV DB_HOST db
ENV DB_PORT 3306

EXPOSE 4000

ENTRYPOINT /usr/local/bin/wait-for ${DB_HOST}:${DB_PORT} --timeout=30 -- /usr/local/bin/dataservice
