FROM golang:1.13.7-alpine AS build

ENV GOPATH /go
WORKDIR /go/src/jaeger-rd/web

COPY web /go/src/jaeger-rd/web

RUN go build -o /go/bin/web -mod=vendor

FROM alpine:3.11.3

COPY --from=build /go/bin/web /usr/local/bin/
COPY static /go/static

EXPOSE 3000

ENTRYPOINT ["/usr/local/bin/web"]
